// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bgColor': string;
  'container': string;
  'ico': string;
  'infDiv': string;
}
export const cssExports: CssExports;
export default cssExports;
