// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'date': string;
  'ico': string;
  'msgText': string;
  'selfMsg': string;
}
export const cssExports: CssExports;
export default cssExports;
