// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'btnContainer': string;
  'container': string;
  'errorInp': string;
  'errorTypeText': string;
  'hr': string;
  'row': string;
}
export const cssExports: CssExports;
export default cssExports;
