// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'btnEditContainer': string;
  'choosedMessageContainer': string;
  'container': string;
  'inpContiner': string;
  'messageContainer': string;
  'txt': string;
}
export const cssExports: CssExports;
export default cssExports;
